Hometask 1
TheNeonLightning/smart-home-2021 pull request #1
Opened 2021-03-10 19:24 UTC by TheNeonLightning

Еременко Илья, Б05-831, SOLID refactoring

2021-03-13 16:47 UTC, a-ivanov requested changes

2021-03-13 16:47 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHomeEventHandler.java
> +public class SmartHomeEventHandler implements EventHandler {
Это выглядит как `god object` по обработке событий. Он усложняет понимание логики обработки, нарушает SRP и OCP. Разделите на классы обработчиков по типу событий с единым интерфейсом.

2021-03-16 11:54 UTC, TheNeonLightning commented on src/main/java/ru/sbt/mipt/oop/SmartHomeEventHandler.java
> +public class SmartHomeEventHandler implements EventHandler {
Добрый день! Думаю, что исправил: теперь есть объект, который содержит обработчики и вызывает их в зависимости от поступивших сигналов, и, собственно, сами классы обработчики с единым интерфейсом.

2021-03-16 16:14 UTC, a-ivanov requested changes

2021-03-16 16:14 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventResolver/SmartHomeEventResolver.java
> +        switch (event.getType()) {
Не совсем так. Теперь вы нарушили OCP:  для добавления новых обработчиков вам необходимо менять код этого класса. Сделайте список обработчиков полем, предлагайте каждому из них обработать событие. Обработчик сам будет решать, какие события он сможет обработать.

2021-03-16 19:55 UTC, TheNeonLightning commented on src/main/java/ru/sbt/mipt/oop/EventResolver/SmartHomeEventResolver.java
> +        switch (event.getType()) {
Добрый вечер! Внес изменения.

2021-03-17 06:10 UTC, a-ivanov approved these changes

2021-03-17 06:10 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHomeUtility.java
> +    public static Room findRoom(SmartHome home, String doorId) {
Утилиты обычно делают, когда надо переиспользовать код. Мне кажется, тут достаточно узкий use case, и можно это перенести  в обработчик.

2021-04-18 17:17 UTC, merged