Hometask 2
TheNeonLightning/smart-home-2021 pull request #3
Opened 2021-03-21 08:35 UTC by TheNeonLightning

Еременко Илья, пересоздаю pull request на этот раз уже в мастер. (Я не понял сначала, что мне сразу нужно это было сделать, поэтому спустя несколько дней).

2021-03-22 06:15 UTC, a-ivanov requested changes
Удалите все методы с доступом к внутренним данным дома (типа getRooms).

2021-04-18 18:03 UTC, TheNeonLightning commented
Добрый вечер! Удалил указанные методы. Они у меня использовались только при тестировании, заменил их на проверку состояния объектов дома с помощью Actionable (классы DoorChecker и LightChecker в тестах).

2021-04-20 13:48 UTC, a-ivanov approved these changes

2021-04-20 13:48 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome/SmartHome.java
> +    Collection<Room> rooms;
private, инкапсуляция

2021-05-25 10:17 UTC, merged