Hometask 3
TheNeonLightning/smart-home-2021 pull request #4
Opened 2021-03-24 20:41 UTC by TheNeonLightning

Еременко Илья, не успел покрыть Unit тестами...

2021-03-29 16:43 UTC, a-ivanov requested changes

2021-03-29 16:43 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Signalization/Alarm.java
> +public class Alarm extends State {
Перечитайте, как имплементировать шаблон состояние через интерфейсы состояний и классы, перепишите свой код.

2021-03-29 16:43 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventProcessor/SignalizationEventProcessorDecorator.java
> +    private void sendMessage() {
В отдельный класс с интерфейсом.

2021-03-29 16:43 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventProcessor/SignalizationEventProcessorDecorator.java
> +        if (signalization.stateType() == ACTIVATED) {
См. Обсуждение в группе, переделайте на метод в сигнализации без состояния.

2021-04-27 13:05 UTC, TheNeonLightning commented
Добрый день! Думаю, что исправил недочёты: состояние теперь через интерфейc, добавил интерфейс и класс ContinuousNotifier для посылки сообщений, убрал работу с состояниями в сигнализацию.

2021-04-28 06:14 UTC, a-ivanov requested changes

2021-04-28 06:14 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Signalization/State.java
> +    StateType stateType();
Зачем поддерживать ещё один енум? Удалите, проверять состояние можно с помощью instanceof.

2021-04-28 06:14 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Notification/SMSContinuousNotifier.java
> +                Thread.sleep(sleepBreak);
Это зачем? Такого не было по заданию, удалите.

2021-04-28 06:14 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventProcessor/SignalizationEventProcessorDecorator.java
> +                                                ContinuousNotifier notifier) {
Используйте интерфейс Notifier, без конкретного класса. DIP.

2021-04-29 15:30 UTC, TheNeonLightning commented
State enum удалил, проверяю по instanceof. Также избавился от засыпания в notifier.

2021-04-29 15:30 UTC, TheNeonLightning commented on src/main/java/ru/sbt/mipt/oop/EventProcessor/SignalizationEventProcessorDecorator.java
> +                                                ContinuousNotifier notifier) {
Добрый день! ContinuousNotifier у меня тоже является интерфейсом: для отправки уведомлений я создал два интерфейса, Notifier и ContinuousNotifier. Первый отвечает за логику отправки одного сообщения, второй отвечает за логику продолжительной отправки сообщений. Внутри реализации ContinuousNotifierImpl используется произвольная реализация интерфейса Notifier. Так я, думаю, что разделяю ответственность следуя SRP. Стоит ли это исправить на один интерфейс Notifier?

2021-05-06 10:16 UTC, a-ivanov approved these changes

2021-05-25 10:47 UTC, closed without merging