Hometask 4
TheNeonLightning/smart-home-2021 pull request #5
Opened 2021-04-07 22:10 UTC by TheNeonLightning

Еременко Илья, Б05-831

2021-04-09 16:38 UTC, a-ivanov requested changes

2021-04-09 16:38 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ApplicationConfiguration.java
> +        EventProcessor eventProcessor =
См. Гайд, сделайте список бинов. Сейчас это нарушение OCP на уровне конфигурации.

2021-04-09 16:38 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/CCEventHandlerAdapter.java
> +        return switch (eventType) {
Нарушение OCP, используйте мапу

2021-04-29 17:37 UTC, TheNeonLightning commented
Здравствуйте! Исправил обе ошибки.

2021-05-06 10:18 UTC, a-ivanov requested changes

2021-05-06 10:18 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/CCEventHandlerAdapter.java
> +        return switch (eventType) {
Не исправлено

2021-05-06 10:28 UTC, TheNeonLightning commented
Здравствуйте! Забыл удалить старый не использующийся метод, саму ошибку исправил: использую мапу.

2021-05-06 11:25 UTC, a-ivanov approved these changes

2021-05-25 11:28 UTC, merged